Correct bugs in execution summary (#183)
Two related issues. One was a bug in the production code, the other a
bug in the test.

Failures were being included as "skipped" in the summary.
---

Previously, if a group failed, we would get this output.

```console
Summary: 0 groups succeeded, 1 groups failed, 1 groups skipped
```

This was incorrect as the group failed and nothing was skipped.

This was the output from the test prior to fixing the bug.

```console
---- doctor::runner::tests::test_execute_dep_fails_wont_run_others stdout ----
thread 'doctor::runner::tests::test_execute_dep_fails_wont_run_others' panicked at scope/src/doctor/runner.rs:636:9:
assertion `left == right` failed
  left: {"skipped_1", "skipped_2"}
 right: {"fails", "skipped_1", "skipped_2"}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Test for non-required action was incorrect
---

The test setup for this test was incorrect

```console
---- doctor::runner::tests::test_execute_branch_fails_but_other_branch_continues stdout ----
thread 'doctor::runner::tests::test_execute_branch_fails_but_other_branch_continues' panicked at scope/src/doctor/runner.rs:664:9:
assertion `left == right` failed
  left: {"succeeds_1", "succeeds_2"}
 right: {"succeeds_1"}
```

The `failed` action was being marked as `required`


https://github.com/oscope-dev/scope/blob/419291a7b5074a5c88b430b989de06dadf647f30/scope/src/doctor/runner.rs#L551

but to test this, the action needed to be non-required to allow
execution to continue onto the next action.
This also means that the following action woudn't be skipped.