Correct bugs in execution summary
- Failures were being included as "skipped" in the summary.
- Test for non-required action was incorrect

This was the output from the tests after increasing the test coverage (and before fixing the bugs).

```console
---- doctor::runner::tests::test_execute_dep_fails_wont_run_others stdout ----
thread 'doctor::runner::tests::test_execute_dep_fails_wont_run_others' panicked at scope/src/doctor/runner.rs:636:9:
assertion `left == right` failed
  left: {"skipped_1", "skipped_2"}
 right: {"fails", "skipped_1", "skipped_2"}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- doctor::runner::tests::test_execute_branch_fails_but_other_branch_continues stdout ----
thread 'doctor::runner::tests::test_execute_branch_fails_but_other_branch_continues' panicked at scope/src/doctor/runner.rs:664:9:
assertion `left == right` failed
  left: {"succeeds_1", "succeeds_2"}
 right: {"succeeds_1"}
```